package edu.towson.cis.cosc442.project1.monopoly.gui;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.*;

import edu.towson.cis.cosc442.project1.monopoly.RespondDialog;
import edu.towson.cis.cosc442.project1.monopoly.TradeDeal;

public class GUIRespondDialog extends JDialog implements RespondDialog {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private boolean response;
    JTextArea txtMessage = new JTextArea();

    /**
     * Constructs a modal dialog with Yes and No buttons and a message display area
     * for user responses.
     */
    public GUIRespondDialog() {
        JButton btnYes = new JButton("Yes");
        JButton btnNo = new JButton("No");
        txtMessage.setPreferredSize(new Dimension(300, 200));
        txtMessage.setEditable(false);
        txtMessage.setLineWrap(true);

        Container contentPane = getContentPane();
        contentPane.setLayout(new BorderLayout());
        contentPane.add(txtMessage, BorderLayout.CENTER);
        JPanel pnlButtons = new JPanel();
        pnlButtons.add(btnYes);
        pnlButtons.add(btnNo);
        contentPane.add(pnlButtons, BorderLayout.SOUTH);

        btnYes.addActionListener(new ActionListener() {
            @SuppressWarnings("deprecation")
            /**
             * Handles the action event by setting the response to false and hiding the
             * dialog when the No button is pressed.
             * 
             * @param e the event generated by pressing the No button
             */
            public void actionPerformed(ActionEvent e) {
                response = true;
                hide();
            }
        });

        btnNo.addActionListener(new ActionListener() {
            @SuppressWarnings("deprecation")
            /**
             * Handles the action event by setting the response to false and hiding the
             * dialog when the No button is pressed.
             * 
             * @param e the event generated by pressing the No button
             */
            public void actionPerformed(ActionEvent e) {
                response = false;
                hide();
            }
        });

        setModal(true);
        pack();
    }

    /**
     * Returns the boolean response indicating user's choice from the dialog.
     * 
     * @return the user's response as true for Yes and false for No
     */
    public boolean getResponse() {
        return response;
    }

    /**
     * Sets the dialog's message text based on the provided trade deal's message.
     * 
     * @param deal the trade deal used to generate the dialog message
     */
    public void setDeal(TradeDeal deal) {
        txtMessage.setText(deal.makeMessage());
    }

}
